//
// Created by Raul on 5/22/2022.
//

#ifndef SDTOYSOCIALNETWORK_TESTFRIENDSHIPSERVICE_H
#define SDTOYSOCIALNETWORK_TESTFRIENDSHIPSERVICE_H

void testAllFriendshipService();

#endif //SDTOYSOCIALNETWORK_TESTFRIENDSHIPSERVICE_H
