//
// Created by Raul on 5/19/2022.
//

#ifndef SDTOYSOCIALNETWORK_TESTFRIENDSHIP_H
#define SDTOYSOCIALNETWORK_TESTFRIENDSHIP_H

void testAllFriendShip();

#endif //SDTOYSOCIALNETWORK_TESTFRIENDSHIP_H
