//
// Created by Raul on 5/22/2022.
//

#ifndef SDTOYSOCIALNETWORK_TESTEVENTSERVICE_H
#define SDTOYSOCIALNETWORK_TESTEVENTSERVICE_H

void testAllEventService();

#endif //SDTOYSOCIALNETWORK_TESTEVENTSERVICE_H
