//
// Created by Raul on 5/20/2022.
//

#ifndef SDTOYSOCIALNETWORK_TESTITERATOR_H
#define SDTOYSOCIALNETWORK_TESTITERATOR_H

void testAllIterator();

#endif //SDTOYSOCIALNETWORK_TESTITERATOR_H
