//
// Created by Raul on 5/8/2022.
//

#ifndef SDTOYSOCIALNETWORK_TESTBINARYSEARCHTREE_H
#define SDTOYSOCIALNETWORK_TESTBINARYSEARCHTREE_H

void testAllBST();

#endif //SDTOYSOCIALNETWORK_TESTBINARYSEARCHTREE_H
