//
// Created by Raul on 5/22/2022.
//

#ifndef SDTOYSOCIALNETWORK_TESTUSERSERVICE_H
#define SDTOYSOCIALNETWORK_TESTUSERSERVICE_H

void testAllUserService();

#endif //SDTOYSOCIALNETWORK_TESTUSERSERVICE_H
